### PR TITLE
Feat: Factory tests implemented

### PR DESCRIPTION
**Pull request by cbrzn**

### CODE REVIEW

**Comment by cbrzn** [comment]
The CI is failing on this PR. I would like to merge first #5 and then update this branch

**Comment by auryn-macmillan** [comment]
I don't think we should do the tests on Rinkeby. Is there a reason we cannot do them in with the hardhat network?

**Comment by auryn-macmillan** [comment]
If we must test on Rineby, then we should add dotenv and a [sample ENV file](https://github.com/gnosis/dao-module/blob/main/.env.sample).

**Comment by cbrzn** [comment]
We are forking rinkeby chain and then testing it in hardhat network - The reason is that the master copies and factory are already deployed, and we are not redeploying anything, just interacting with existing copies and factory.

Do you think it will be worth creating a deployment fixture of the dao module and then use that on the tests? @auryn-macmillan

**Pull request merged**
